default:
  proxy:
    - host: 10.0.10.1
      port: 9390
10000:
  proxy:
    - host: 10.0.10.1
      port: 9390
  fateflow:
    - host: 10.0.10.1
      port: 9360
9999:
  proxy:
    - host: 10.0.10.2
      port: 9390
  fateflow:
    - host: 10.0.10.2
      port: 9360